steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/%%IMAGE_NAME%%:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', '%%IMAGE_NAME%%:base',
    '-t', 'gcr.io/$PROJECT_ID/%%IMAGE_NAME%%:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/%%IMAGE_NAME%%:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/%%IMAGE_NAME%%:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/%%IMAGE_NAME%%:latest',
    '.'
  ]
images: ['gcr.io/$PROJECT_ID/%%IMAGE_NAME%%:base', 'gcr.io/$PROJECT_ID/%%IMAGE_NAME%%:latest']
