steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/cracking-the-web:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'cracking-the-web:base',
    '-t', 'gcr.io/$PROJECT_ID/cracking-the-web:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/cracking-the-web:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cracking-the-web:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/cracking-the-web:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/cracking-the-web:coverage',
    '.'
  ]
images: [
  'gcr.io/$PROJECT_ID/cracking-the-web:base',
  'gcr.io/$PROJECT_ID/cracking-the-web:latest',
  'gcr.io/$PROJECT_ID/cracking-the-web:coverage'
]
